"""
===============================================================================
TETHYS 2026 | Hands-on Training
By GEA Computing Ltd
===============================================================================

Download a small Mediterranean sea-surface-temperature subset with the
Copernicus Marine Toolbox.

This immediately runnable request was generated by the Copernicus Marine
product page's Download section after the basic dataset, variable, geographic,
and time selections were entered. The generated parameters are kept below so
they can be compared directly with the choices in the web interface.

Prerequisites:
    pip install copernicusmarine
    copernicusmarine login

The login command stores the user's Copernicus Marine credentials locally. Do
not add usernames or passwords to this script. This script checks the saved
credentials before requesting data. Run the script with:
    python code/py/Intro_Marine.py

Source:
    https://data.marine.copernicus.eu/product/SST_MED_SST_L4_NRT_OBSERVATIONS_010_004/description

-- Copernicus Marine --
Last tested on 1 Oct 2026.
===============================================================================
"""

import copernicusmarine

try:
    valid = copernicusmarine.login(check_credentials_valid=True)
except Exception as error:
    print("✗ Credentials could not be checked")
    print(
        "\nCheck your internet connection, then run `copernicusmarine login` "
        "in a terminal and sign in with your Copernicus Marine account. "
        f"Validation detail: {error}"
    )
    raise SystemExit(1) from error

print("✓ Credentials valid" if valid else "✗ Credentials missing or invalid")

if not valid:
    print(
        "\nThe download cannot start because Copernicus Marine credentials are "
        "missing, expired, or incorrect. Run `copernicusmarine login` in a "
        "terminal, sign in with your Copernicus Marine account, then run this "
        "script again."
    )
    raise SystemExit(1)


# Download analysed sea-surface temperature (SST) from the Mediterranean
# near-real-time Level-4 observation product.
response = copernicusmarine.subset(
    dataset_id="SST_MED_SST_L4_NRT_OBSERVATIONS_010_004_c_V2",  # Dataset selected on the Copernicus Marine product page.
    dataset_version="202311",  # Product version selected on the product page.
    variables=["analysed_sst"],  # Download analysed SST only.
    minimum_longitude=30.68,  # Western edge of the Cyprus-area bounding box (decimal degrees).
    maximum_longitude=36.15,  # Eastern edge of the Cyprus-area bounding box (decimal degrees).
    minimum_latitude=32.32,  # Southern edge of the Cyprus-area bounding box (decimal degrees).
    maximum_latitude=36.72,  # Northern edge of the bounding box (decimal degrees).
    start_datetime="2026-09-01T00:00:00",  # Start of the requested UTC time interval.
    end_datetime="2026-09-02T00:00:00",  # End of the requested UTC time interval.
    coordinates_selection_method="strict-inside",  # Keep grid cells strictly inside the selected area.
    netcdf_compression_level=5,  # Use moderate compression for the NetCDF output.
    disable_progress_bar=False,  # Show download progress in the terminal.
)

# The response records the locally created file(s) and transfer details.
print("\nDownload completed.")
print(response)
